name: Auto Merge Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git remote add upstream https://github.com/IntellectualSites/PlotSquared

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin main

      - name: Cleanup
        run: |
          git remote remove upstream
